[package]
name = "citation-sentiment"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-bert = "0.23.0"
pdf-extract = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
regex = "1.11.1"
tokenizers = "0.21.2"
anyhow = "1.0.98"
